lzc-sdk-version: "0.1"
name: RTorrent
package: cloud.lazycat.app.rtorrent
version: 3.21.0
description: 一个BitTorrent 客户端
homepage: https://github.com/rakshasa/rtorrent
author: rakshasa
application:
  subdomain: rtorrent
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://rutorrent.cloud.lazycat.app.rtorrent.lzcapp:80/
  ingress:
    - protocol: tcp
      port: 5000
      service: rutorrent
    - protocol: tcp
      port: 51413
      service: rutorrent
    - protocol: udp
      port: 6881
      service: rutorrent
services:
  rutorrent:
    image: registry.lazycat.cloud/czyt/linuxserver/rutorrent:69b28c66fa8e4887
    environment:
      - PUID=1000
      - PGID=1000
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/downloads:/downloads
      
unsupported_platforms:
  - ios
  - android